//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_EMPLOYEE_DESC
    {
        public string EMPNO { get; set; }
        public string PWD { get; set; }
        public Nullable<int> DEPT { get; set; }
        public string C_NAME { get; set; }
        public Nullable<System.DateTime> IN_TIME { get; set; }
        public Nullable<System.DateTime> OUT_TIME { get; set; }
        public Nullable<bool> STATE { get; set; }
        public string EN_NAME { get; set; }
        public string EMP_ISADMIN { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
