//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PACKING_TABLE
    {
        public string PACKING_HEHAO { get; set; }
        public string PACKING_XIANGHAO { get; set; }
        public string PACKING_ZHANBAN { get; set; }
        public string ZHUANGHENUM { get; set; }
        public string MUBIAONUM { get; set; }
        public Nullable<System.DateTime> CHANGER_DATE { get; set; }
    }
}
