//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_PRIVILEGE_DESC
    {
        public string EMPNO { get; set; }
        public Nullable<bool> A_S { get; set; }
        public Nullable<bool> H_M { get; set; }
        public Nullable<bool> TAURUS { get; set; }
        public Nullable<bool> EXCA { get; set; }
        public Nullable<bool> B9 { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<bool> AUSTIN { get; set; }
        public Nullable<bool> CRETE { get; set; }
    }
}
