//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_MODEL_LINK
    {
        public string LINK_ID { get; set; }
        public string BG_CODE { get; set; }
        public string FACTORY_CODE { get; set; }
        public string MODEL_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public decimal LINK_ENABLE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
