//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_DASHBOARD_REPORT_TYPE
    {
        public string REPORT_ID { get; set; }
        public string REPORT_NAME { get; set; }
        public string MODEL_NAME { get; set; }
        public string REPORT_TYPE { get; set; }
        public Nullable<System.DateTime> DTTM { get; set; }
        public Nullable<decimal> REPORT_ENABLE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
