//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_PDLINE_PASS_QTY_TEST
    {
        public Nullable<System.DateTime> CURRENT_TIME { get; set; }
        public string MODEL_NAME { get; set; }
        public string PDLINE_ID { get; set; }
        public decimal PASS_QTY { get; set; }
        public decimal IDLE_TIME { get; set; }
        public decimal CURRENT_HOUR { get; set; }
    }
}
