//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_SHIPPING_INFOS
    {
        public string DATE_ID { get; set; }
        public string MODEL_NO { get; set; }
        public string ERP_DATE { get; set; }
        public Nullable<decimal> SFC_COMP_QTY { get; set; }
        public Nullable<decimal> ERP_COMP_QTY { get; set; }
        public Nullable<decimal> ERP_SHIP_QTY { get; set; }
    }
}
