//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FoxlinkSfcContext : DbContext
    {
        public FoxlinkSfcContext()
            : base("name=FoxlinkSfcContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_EMPLOYEE_DESC> A_EMPLOYEE_DESC { get; set; }
        public virtual DbSet<A_PACKING_TABLE> A_PACKING_TABLE { get; set; }
        public virtual DbSet<BG_MODEL_LINK> BG_MODEL_LINK { get; set; }
        public virtual DbSet<FL_DASHBOARD_REPORT_TYPE> FL_DASHBOARD_REPORT_TYPE { get; set; }
        public virtual DbSet<FOXLINK_OEE> FOXLINK_OEE { get; set; }
        public virtual DbSet<JOB_EXECUTE_LOG> JOB_EXECUTE_LOG { get; set; }
        public virtual DbSet<MODEL_RPT_LINK> MODEL_RPT_LINK { get; set; }
        public virtual DbSet<PACK_SECTION_TOTAL_CAPACITY> PACK_SECTION_TOTAL_CAPACITY { get; set; }
        public virtual DbSet<PACK_SECTION_TOTAL_PRODUCTION> PACK_SECTION_TOTAL_PRODUCTION { get; set; }
        public virtual DbSet<REPORT_GROUPS> REPORT_GROUPS { get; set; }
        public virtual DbSet<REPORT_ITEMS> REPORT_ITEMS { get; set; }
        public virtual DbSet<SHIPPING_INFOS> SHIPPING_INFOS { get; set; }
        public virtual DbSet<SMT_AVG_OEE_INFOS> SMT_AVG_OEE_INFOS { get; set; }
        public virtual DbSet<SMT_IDLE_TIME_INFOS> SMT_IDLE_TIME_INFOS { get; set; }
        public virtual DbSet<SMT_OEE_BY_PDLINE> SMT_OEE_BY_PDLINE { get; set; }
        public virtual DbSet<SMT_UPH_BY_PDLINE> SMT_UPH_BY_PDLINE { get; set; }
        public virtual DbSet<A_PRIVILEGE_DESC> A_PRIVILEGE_DESC { get; set; }
        public virtual DbSet<FL_PDLINE_PASS_QTY_HISTORY> FL_PDLINE_PASS_QTY_HISTORY { get; set; }
        public virtual DbSet<FL_PDLINE_PASS_QTY_TEST> FL_PDLINE_PASS_QTY_TEST { get; set; }
        public virtual DbSet<FL_SHIPPING_INFOS> FL_SHIPPING_INFOS { get; set; }
        public virtual DbSet<FOXLINK_OEE_20160819_BAK> FOXLINK_OEE_20160819_BAK { get; set; }
        public virtual DbSet<FOXLINK_OEE_BACKUP> FOXLINK_OEE_BACKUP { get; set; }
        public virtual DbSet<RC_RESOURCES_ALL> RC_RESOURCES_ALL { get; set; }
        public virtual DbSet<RC_WORKING_HOURS> RC_WORKING_HOURS { get; set; }
        public virtual DbSet<AS_SMT_PAST10D_OEE_VALUE> AS_SMT_PAST10D_OEE_VALUE { get; set; }
        public virtual DbSet<B9_SMT_PAST10D_OEE_VALUE> B9_SMT_PAST10D_OEE_VALUE { get; set; }
        public virtual DbSet<EXC_SMT_PAST10D_OEE_VALUE> EXC_SMT_PAST10D_OEE_VALUE { get; set; }
        public virtual DbSet<HM_SMT_PAST10D_OEE_VALUE> HM_SMT_PAST10D_OEE_VALUE { get; set; }
    
        public virtual int GET_AS_NEW_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_AS_NEW_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_AS_NEW_TOTAL_CAPACITY(string tIME_INTERVAL)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_AS_NEW_TOTAL_CAPACITY", tIME_INTERVALParameter);
        }
    
        public virtual int GET_AS_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_AS_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_AS_TOTAL_PACK_CAPACITY(string tIME_INTERVAL, string mODEL_NO)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_AS_TOTAL_PACK_CAPACITY", tIME_INTERVALParameter, mODEL_NOParameter);
        }
    
        public virtual int GET_AUSTIN_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_AUSTIN_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_B9_NEW_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_B9_NEW_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_B9_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_B9_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_B9_SMT_PASS_QTY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_B9_SMT_PASS_QTY");
        }
    
        public virtual int GET_B9_TOTAL_PACK_CAPACITY(string tIME_INTERVAL, Nullable<decimal> iS_TOTAL_CAPACITY)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            var iS_TOTAL_CAPACITYParameter = iS_TOTAL_CAPACITY.HasValue ?
                new ObjectParameter("IS_TOTAL_CAPACITY", iS_TOTAL_CAPACITY) :
                new ObjectParameter("IS_TOTAL_CAPACITY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_B9_TOTAL_PACK_CAPACITY", tIME_INTERVALParameter, iS_TOTAL_CAPACITYParameter);
        }
    
        public virtual int GET_CASTOR_CAPACITY(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_CASTOR_CAPACITY", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_CRETE_TOTAL_PACK_CAPACITY(string tIME_INTERVAL, Nullable<decimal> iS_TOTAL_CAPACITY)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            var iS_TOTAL_CAPACITYParameter = iS_TOTAL_CAPACITY.HasValue ?
                new ObjectParameter("IS_TOTAL_CAPACITY", iS_TOTAL_CAPACITY) :
                new ObjectParameter("IS_TOTAL_CAPACITY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_CRETE_TOTAL_PACK_CAPACITY", tIME_INTERVALParameter, iS_TOTAL_CAPACITYParameter);
        }
    
        public virtual int GET_EXCALIBUR_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_EXCALIBUR_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_EXCA_TOTAL_PACK_CAPACITY(string tIME_INTERVAL, Nullable<decimal> iS_TOTAL_CAPACITY)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            var iS_TOTAL_CAPACITYParameter = iS_TOTAL_CAPACITY.HasValue ?
                new ObjectParameter("IS_TOTAL_CAPACITY", iS_TOTAL_CAPACITY) :
                new ObjectParameter("IS_TOTAL_CAPACITY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_EXCA_TOTAL_PACK_CAPACITY", tIME_INTERVALParameter, iS_TOTAL_CAPACITYParameter);
        }
    
        public virtual int GET_EXC_SMT_PASS_QTY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_EXC_SMT_PASS_QTY");
        }
    
        public virtual int GET_HM_NEW_PACK_CAPACITY(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_HM_NEW_PACK_CAPACITY", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_HM_NEW_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_HM_NEW_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_HM_NEW_SMT_CAPACITY(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_HM_NEW_SMT_CAPACITY", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_HM_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_HM_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_HM_TOTAL_CAPACITY(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_HM_TOTAL_CAPACITY", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_OVERVIEW_SMT_OEE_EXCLUDE(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_OVERVIEW_SMT_OEE_EXCLUDE", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_OVERVIEW_SMT_SECTION_OEE(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_OVERVIEW_SMT_SECTION_OEE", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_PACK_SECTION_LINE_INFOS(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PACK_SECTION_LINE_INFOS", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_PACK_TOTAL_PRODUCTION(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PACK_TOTAL_PRODUCTION", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_POLLUX_CAPACITY(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_POLLUX_CAPACITY", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_RC_DATAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_RC_DATAS");
        }
    
        public virtual int GET_RC_TOTAL_CAPACITY(string mODEL_NO, Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_RC_TOTAL_CAPACITY", mODEL_NOParameter, sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE, Nullable<decimal> oRG_ID)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            var oRG_IDParameter = oRG_ID.HasValue ?
                new ObjectParameter("ORG_ID", oRG_ID) :
                new ObjectParameter("ORG_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter, oRG_IDParameter);
        }
    
        public virtual int GET_SMT_EQUIP_OEE_INTERVAL(string mODEL_NO, string lINE_NAME, Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var lINE_NAMEParameter = lINE_NAME != null ?
                new ObjectParameter("LINE_NAME", lINE_NAME) :
                new ObjectParameter("LINE_NAME", typeof(string));
    
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_EQUIP_OEE_INTERVAL", mODEL_NOParameter, lINE_NAMEParameter, sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_SMT_LINE_INFOS(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_LINE_INFOS", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_SMT_LINE_OEE_UPH(string mODEL_NO, string lINE_NAME, string lINE_ID, Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var lINE_NAMEParameter = lINE_NAME != null ?
                new ObjectParameter("LINE_NAME", lINE_NAME) :
                new ObjectParameter("LINE_NAME", typeof(string));
    
            var lINE_IDParameter = lINE_ID != null ?
                new ObjectParameter("LINE_ID", lINE_ID) :
                new ObjectParameter("LINE_ID", typeof(string));
    
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_LINE_OEE_UPH", mODEL_NOParameter, lINE_NAMEParameter, lINE_IDParameter, sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_SMT_LINE_UPH(string mODEL_NO, string lINE_ID, Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var lINE_IDParameter = lINE_ID != null ?
                new ObjectParameter("LINE_ID", lINE_ID) :
                new ObjectParameter("LINE_ID", typeof(string));
    
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_LINE_UPH", mODEL_NOParameter, lINE_IDParameter, sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_SMT_OEE_INTERVAL_EXCLUDE(string mODEL_NO, string lINE_NAME, Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var lINE_NAMEParameter = lINE_NAME != null ?
                new ObjectParameter("LINE_NAME", lINE_NAME) :
                new ObjectParameter("LINE_NAME", typeof(string));
    
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_OEE_INTERVAL_EXCLUDE", mODEL_NOParameter, lINE_NAMEParameter, sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_SMT_SECTION_EQUIP_OEE(string mODEL_NO)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_SECTION_EQUIP_OEE", mODEL_NOParameter);
        }
    
        public virtual int GET_SMT_SECTION_LINE_STATUS(string mODEL_NO)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_SECTION_LINE_STATUS", mODEL_NOParameter);
        }
    
        public virtual int GET_SMT_TOTAL_CAPACITY(string mODEL_NO, string tIME_INTERVAL, Nullable<decimal> iS_TOTAL_CAPACITY)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            var iS_TOTAL_CAPACITYParameter = iS_TOTAL_CAPACITY.HasValue ?
                new ObjectParameter("IS_TOTAL_CAPACITY", iS_TOTAL_CAPACITY) :
                new ObjectParameter("IS_TOTAL_CAPACITY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_TOTAL_CAPACITY", mODEL_NOParameter, tIME_INTERVALParameter, iS_TOTAL_CAPACITYParameter);
        }
    
        public virtual int GET_SMT_TOTAL_PRODUTION_AMOUNT(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_TOTAL_PRODUTION_AMOUNT", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_SMT_TOTAL_PROD_AMOUNT(string mODEL_NO, string tIME_INTERVAL)
        {
            var mODEL_NOParameter = mODEL_NO != null ?
                new ObjectParameter("MODEL_NO", mODEL_NO) :
                new ObjectParameter("MODEL_NO", typeof(string));
    
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SMT_TOTAL_PROD_AMOUNT", mODEL_NOParameter, tIME_INTERVALParameter);
        }
    
        public virtual int GET_TAURUS_NEW_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TAURUS_NEW_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_TAURUS_PACK_CAPACITY(string tIME_INTERVAL, Nullable<decimal> iS_TOTAL_CAPACITY)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            var iS_TOTAL_CAPACITYParameter = iS_TOTAL_CAPACITY.HasValue ?
                new ObjectParameter("IS_TOTAL_CAPACITY", iS_TOTAL_CAPACITY) :
                new ObjectParameter("IS_TOTAL_CAPACITY", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TAURUS_PACK_CAPACITY", tIME_INTERVALParameter, iS_TOTAL_CAPACITYParameter);
        }
    
        public virtual int GET_TAURUS_SHIPPING_INFOS(Nullable<System.DateTime> sTART_DATE, Nullable<System.DateTime> eND_DATE)
        {
            var sTART_DATEParameter = sTART_DATE.HasValue ?
                new ObjectParameter("START_DATE", sTART_DATE) :
                new ObjectParameter("START_DATE", typeof(System.DateTime));
    
            var eND_DATEParameter = eND_DATE.HasValue ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TAURUS_SHIPPING_INFOS", sTART_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int GET_TAURUS_TOTAL_PACK_CAPACITY(string tIME_INTERVAL)
        {
            var tIME_INTERVALParameter = tIME_INTERVAL != null ?
                new ObjectParameter("TIME_INTERVAL", tIME_INTERVAL) :
                new ObjectParameter("TIME_INTERVAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TAURUS_TOTAL_PACK_CAPACITY", tIME_INTERVALParameter);
        }
    
        public virtual int SET_AS_SHIP_DATA_INTO_DB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SET_AS_SHIP_DATA_INTO_DB");
        }
    
        public virtual int SET_AUSTIN_SHIPPING_INFOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SET_AUSTIN_SHIPPING_INFOS");
        }
    
        public virtual int SET_B9_SHIPPING_INFOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SET_B9_SHIPPING_INFOS");
        }
    
        public virtual int SET_HM_SHIP_INFOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SET_HM_SHIP_INFOS");
        }
    
        public virtual int SET_TAURUS_SHIP_INFOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SET_TAURUS_SHIP_INFOS");
        }
    }
}
