//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOXLINK_OEE_20160819_BAK
    {
        public string PDLINE_ID { get; set; }
        public Nullable<decimal> IDLE_MINUTE { get; set; }
        public Nullable<System.DateTime> DTTM { get; set; }
        public string MODEL_NAME { get; set; }
        public Nullable<decimal> OEE_VALUE { get; set; }
    }
}
