//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_EXECUTE_LOG
    {
        public string PROCEDURE_NAME { get; set; }
        public Nullable<System.DateTime> EXECUTE_BEGIN_TIME { get; set; }
        public string EXECUTE_STATUS { get; set; }
        public string EXECUTE_STATUS_DETAILS { get; set; }
        public Nullable<System.DateTime> EXECUTE_END_TIME { get; set; }
        public string LOG_UUID { get; set; }
    }
}
