//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_RESOURCES_ALL
    {
        public long RC_RESOURCE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public string RESOURCE_CATEGORY { get; set; }
        public string DESCRIPTION { get; set; }
        public string UOM_CODE { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public Nullable<decimal> BOM_DEPARTMENT_ID { get; set; }
        public Nullable<decimal> BOM_RESOURCE_ID { get; set; }
        public long ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public long LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public Nullable<long> LAST_UPDATE_LOGIN { get; set; }
        public string ATTRIBUTE_CATEGORY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public string PROD_LINE_CODE { get; set; }
        public Nullable<decimal> ASSET_ID { get; set; }
        public string SPC_DESCRIPTION { get; set; }
        public string SOURCE_TYPE { get; set; }
        public Nullable<decimal> ASSIGN_TO_USER_ID { get; set; }
        public Nullable<decimal> INVENTORY_ITEM_ID { get; set; }
        public Nullable<decimal> ORIGINAL_QTY { get; set; }
        public Nullable<decimal> ONHAND_QTY { get; set; }
        public Nullable<decimal> RESOURCE_COST { get; set; }
        public Nullable<System.DateTime> DATE_IN_SERVICE { get; set; }
        public string MATERIAL_TYPE { get; set; }
        public string CAVE_NO { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public string NOTE4 { get; set; }
        public string NOTE5 { get; set; }
        public Nullable<decimal> ORI_LOCATION_ID { get; set; }
        public string LOT_CONTROL { get; set; }
        public string EMP_CLASS_CODE { get; set; }
        public Nullable<decimal> QA_PLAN_ID { get; set; }
        public string MAINTAIN_JUDGE_TYPE { get; set; }
        public Nullable<decimal> MAINTAIN_INTERVAL { get; set; }
        public Nullable<decimal> LIFESPAN { get; set; }
        public Nullable<decimal> EXTEND_LIFESPAN { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string PROD_COUNTRY { get; set; }
        public string PROD_FAMILY { get; set; }
        public Nullable<decimal> SAFETY_STOCK { get; set; }
        public string COST_TYPE { get; set; }
        public Nullable<decimal> MAINTAIN_PLAN_ID { get; set; }
        public string NOTE6 { get; set; }
        public string NOTE7 { get; set; }
        public string NOTE8 { get; set; }
        public string NOTE9 { get; set; }
        public string NOTE10 { get; set; }
        public string NOTE11 { get; set; }
        public string NOTE12 { get; set; }
        public string NOTE13 { get; set; }
        public string NOTE14 { get; set; }
        public string NOTE15 { get; set; }
        public string NOTE16 { get; set; }
        public string NOTE17 { get; set; }
        public string NOTE18 { get; set; }
        public string NOTE19 { get; set; }
        public string NOTE20 { get; set; }
        public string APPLY_MANDATORY_FLAG { get; set; }
        public string MOLD_NUMBER { get; set; }
        public string HARDNESS { get; set; }
        public string EXTENSION { get; set; }
        public Nullable<decimal> ENG_USER_ID { get; set; }
        public Nullable<decimal> DESIGNER_USER_ID { get; set; }
        public Nullable<decimal> ASSEMBLY_ITEM_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CHARGE_SOURCE { get; set; }
        public string STANDARD_MFG_RATE { get; set; }
        public string CATEGORY1 { get; set; }
        public string CATEGORY2 { get; set; }
        public string CATEGORY3 { get; set; }
        public string CATEGORY4 { get; set; }
        public string CATEGORY5 { get; set; }
        public string HOLD_FLAG { get; set; }
        public string HOLD_REASON { get; set; }
        public Nullable<decimal> PRIMARY_MTL_ITEM_ID { get; set; }
        public Nullable<decimal> MOLD_QTY_PER_ASSEMBLY { get; set; }
        public Nullable<decimal> MOLD_REAL_QTY_PER_ASSEMBLY { get; set; }
        public Nullable<decimal> MOLD_GOOD_CAVE { get; set; }
        public string QUOTATION_CONTROL { get; set; }
        public string EQUIP_CATEGORY { get; set; }
        public string EQUIP_ONLINE_FLAG { get; set; }
    }
}
