//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMT_IDLE_TIME_INFOS
    {
        public string LINK_ID { get; set; }
        public string LINE_ID { get; set; }
        public System.DateTime CURRENT_TIME { get; set; }
        public decimal PASS_QTY { get; set; }
        public decimal IDLE_TIME { get; set; }
        public decimal CURRENT_HOUR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
    }
}
